### PR TITLE
removed clang symlinks

### LINKED ISSUE #8: szcc doesn't work from /usr/bin
I don't think that it is a good idea to check existence of `clang` at the same path. It makes impossible to install `szcc` to a system dir.

https://github.com/Dead2/stabilizer/blob/115c2f78288df717411e1fff641d1d5fb8edcdfb/szcc#L36-L37

### PR DESCRIPTION
**Pull request by magras**
fixes #8

### CODE REVIEW

**Comment by Dead2** [comment]
If we go this route, we would need to rewrite the readme to match this.

But perhaps we could instead make an improved check that detects whether `clang` is actually `szcc` in disguise.
One way would be to check whether it is a symlink that links to self, but that would only work for symlinks and not if
the clang file was instead a copy of szcc. Another alternative could be to search the clang file for a known string that we then know means it is szcc and not the real clang.
Perhaps it would be even better to run the potential "clang" with a parameter that makes szcc return a specific retcode, thus letting us know to ignore that one.

I would ultimately prefer to keep the clang aliases, as those are in some cases easier to use where it is hard or almost impossible to edit multi-level buildsystems that hardcodes the compiler detection. Such as CMake projects with lots of git subprojects each with their own quirky CMake configs, those can be more than a little complicated to get in line and even more of a pain if you expect to pull in upstream changes as well.
In those cases, just changing the path to prefer a szcc folder would be a quick and easy way to test szcc without actually making any lasting changes.

Thoughts?

**Comment by magras** [comment]
> I would ultimately prefer to keep the clang aliases, as those are in some cases easier to use where it is hard or almost impossible to edit multi-level buildsystems that hardcodes the compiler detection. Such as CMake projects with lots of git subprojects each with their own quirky CMake configs, those can be more than a little complicated to get in line and even more of a pain if you expect to pull in upstream changes as well.
> In those cases, just changing the path to prefer a szcc folder would be a quick and easy way to test szcc without actually making any lasting changes.

Won't a simple shell wrapper solve this problem?
```
$ cat clang++
#!/bin/sh
szcc++ "$@"
```

**Comment by Dead2** [comment]
Wouldn't that have the same problem of potentially szcc then calling the shell wrapper thinking that it is the real clang? I don't see how this would actually change anything.

**Comment by Dead2** [comment]
Btw, I'll potentially be away for a couple days, I need to go support someone in a family crisis.
I'll bring my laptop, but whether I get the time to actually use it is as yet unknown.

**Comment by magras** [comment]
> Wouldn't that have the same problem of potentially szcc then calling the shell wrapper thinking that it is the real clang? I don't see how this would actually change anything.

Good point.

May be we could pass clang's location to the `szcc` via an environment variable? The shell script should then find the actual location of clang excluding itself from the search and pass it to the stabilizer. It will also help with "versioned" names (`clang-12`) like in the official deb packages. But there are several binaries looked up by the stabilizer, so it isn't that strait forward.

I don't like my solution that much more than the existing one, so we can postpone the decision if you have no better ideas.

> Btw, I'll potentially be away for a couple days, I need to go support someone in a family crisis. I'll bring my laptop, but whether I get the time to actually use it is as yet unknown.

I wish all the best to your friend and appreciate your time when you have it. Thank you for letting me know in advance.

**Comment by magras** [comment]
Superseded by #30 and #31.

**Pull request closed without merging**
