### PR TITLE
fixed TLS

### LINKED ISSUE #14: crush on attempt to call `__tls_get_addr`
I have no MRE, but `example` binary from zlib-ng crushes because of that.

It turns out in some cases access to a TLS variable can generate an IP relative call on the backend, which of course breaks if the function was relocated at runtime. Since it happens on the compiler backend I don't know how to distinguish cases when stabilizer should keep access to a TLS variable intact and when to replace it.

As always we can replace all accesses to TLS variables with a call to a non-relocatable helper function.

### PR DESCRIPTION
**Pull request by magras**
When code randomization enabled, every access to TLS replaced with a non-relocatable noinline function wrapper.

fixes #14

### CODE REVIEW

**Review by Dead2 — APPROVED** [review]

**Comment by Dead2** [comment]
I didn't actually test this before I merged it, but I noticed now that it does not compile with Clang12.
```
Stabilizer.cpp:735:55: error: too many arguments to function call, expected 0, have 1
                        inst = expr->getAsInstruction(insertion_point);
                               ~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~
/usr/include/llvm/IR/Constants.h:1321:16: note: 'getAsInstruction' declared here
  Instruction *getAsInstruction() const;
               ^
1 error generated.
```

**Comment by magras** [comment]
I fixed it in #24.

But we need to decide what version of llvm we are targeting. In my opinion the latest stable release should be the primary target. I am planing to port stabilizer to llvm-15 after finishing with infrastructure stuff: cmake, tests, docker, ci. And as I said it might be much harder to keep backward compatibility this time.

We can look how other projects using llvm tackle this problem. From the top of my head I can say that include-what-you-use have separate branches for each release of llvm, but I don't know if they backport any changes between them.

**Comment by Dead2** [comment]
I am personally in the process of doing a distro update, that way I will get LLVM 14 support, among others.

Backwards compatibility is a good thing but in this case it is not a blocker IMO. If we are able to support the current stable and 1 or 2 releases before that, that would be ideal. Anything older than that is bound to be a lot of hassle. But it is also a fast moving target, and some distros will be lagging behind (RHEL for example).

Maybe that could be the guideline? That we try to keep support for 1 or 2 previous relseses, but on a best-effort basis. That way we are free to break that backwards support if the changes required are major.
I think this would also make it easier to support installing Stabilizer with multiple llvm versions being used on the same system.
Old versioned releases of Stabilizer could still be downloaded with support for even older llvm versions of course.

What do you think, would this be an OK strategy?

If we do it this way, we should probably also define a keyword to add to comments for any version-based workarounds (`LLVM14` for example), so that we can easily grep and remove workarounds for specific versions. That would perhaps be easiest if it is done by duplicating the affected code in `#ifdef` blocks I think, either by checking for an llvm version define or a buildsystem-supplied one.

**Comment by magras** [comment]
> Backwards compatibility is a good thing but in this case it is not a blocker IMO. If we are able to support the current stable and 1 or 2 releases before that, that would be ideal. Anything older than that is bound to be a lot of hassle. But it is also a fast moving target, and some distros will be lagging behind (RHEL for example).
>
> Maybe that could be the guideline? That we try to keep support for 1 or 2 previous relseses, but on a best-effort basis. That way we are free to break that backwards support if the changes required are major.
> I think this would also make it easier to support installing Stabilizer with multiple llvm versions being used on the same system.
Old versioned releases of Stabilizer could still be downloaded with support for even older llvm versions of course.
>
> What do you think, would this be an OK strategy?

Sounds good to me.

> If we do it this way, we should probably also define a keyword to add to comments for any version-based workarounds (LLVM14 for example), so that we can easily grep and remove workarounds for specific versions. That would perhaps be easiest if it is done by duplicating the affected code in #ifdef blocks I think, either by checking for an llvm version define or a buildsystem-supplied one.

I agree that defines from `llvm/Config/llvm-config.h` should be used. Maybe not as easy to grep for specific version as keywords with version number integrated, but we have very small code base.

Maybe keywords would be useful for small insignificant stuff like #24, but I don't feel the urge right now.

**Comment by magras** [comment]
> LLVM is API-compatible only with matching major.minor versions and patch versions not less than that requested.

It makes strategy proposed by you even more favorable, but complicates `find_package(llvm)` usage in cmake.

**Pull request merged**
