### PR TITLE
port project to cmake

### PR DESCRIPTION
**Pull request by magras**
Cmake doesn't allow different compilers for one language inside a project. To build the tests with stabilizer I extracted them into a separate project.

`tests/Context` and `tests/perlbench` never were part of the build. I left them as is for now.

I enabled exceptions and rtti for the compiler plugin (they were disabled by custom flags) because we are using stl.

### CODE REVIEW

**Comment by magras** [comment]
I don't know cmake very well, so feedback is welcome.

In the current state it is impossible to simply run stabilizer from the source dir. You need to install it, or use the cmake toolchain file. And I don't know how to fix that given out of source build. Technically it's possible to guess the build dir, but I don't like that.

**Comment by nmoinvaz** [comment]
It would be good to do GitHub Actions CI after this PR.

**Comment by Dead2** [comment]
I would suggest adding Cmake support in a separate PR from the removal of the old makefiles.
That would make (regression) testing and comparison easier as we can easily just rebuild with one or the other.
I think this is a very good start, and that we could merge this Cmake code and iterate on it to fix any problems/discrepancies.

Since Stabilizer depends on modern llvm anyway, I agree with the removal of the old makefiles once cmake is proven to be its equivalent or better.

**Comment by magras** [comment]
@Dead2, how much do you value being able to run stabilizer from the source dir? Or maybe a little bit more realistic - from a build dir?

The problem is in order for this to work we need platform specific hacks like `LD_LIBRARY_DIR` or rigid directory structure. I'd rather require proper installation before usage. This is not as convenient for stabilizer developer, but `LD_LIBRARY_DIR` is okay in this context imo. And for me in particular it doesn't matter because I build and test stabilizer in a container.

**Comment by magras** [comment]
Rebased and squashed.

I think I'm done with cmake for now.

Right now tests would not compile because of absolute path to `libLLVMStabilizer.so` (issue #11). Will address it in other pr.

**Comment by magras** [comment]
Added installation of `LICENSE` file.

By the way it isn't filled: https://github.com/Dead2/stabilizer/blob/a117a5782ba128774ca403882010c512f1d9d905/LICENSE#L189

**Comment by Dead2** [comment]
I have some changes I want to make to this, but I'll merge this so I can make a separate PR for the changes 😄

**Pull request merged**
